"""empty message

Revision ID: 46c2b04d5165
Revises: 5ebec89aecd6
Create Date: 2023-05-24 02:28:47.969173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c2b04d5165'
down_revision = '5ebec89aecd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('skin_color', sa.String(length=120), nullable=False),
    sa.Column('eye_color', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('climate', sa.String(length=120), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('Vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('passangers', sa.Integer(), nullable=False),
    sa.Column('vehicle_class', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('FavCharacter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_of_fav', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_of_fav'], ['Character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FavPlanet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_of_fav', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_of_fav'], ['Planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FavVehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_of_fav', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_of_fav'], ['Vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id_char', sa.Integer(), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=True),
    sa.Column('id_vehic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_char'], ['FavCharacter.id'], ),
    sa.ForeignKeyConstraint(['id_plan'], ['FavPlanet.id'], ),
    sa.ForeignKeyConstraint(['id_vehic'], ['FavVehicules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('Favorites')
    op.drop_table('FavVehicules')
    op.drop_table('FavPlanet')
    op.drop_table('FavCharacter')
    op.drop_table('Vehicle')
    op.drop_table('User')
    op.drop_table('Planet')
    op.drop_table('Character')
    # ### end Alembic commands ###
